package request

type Endpoint int

const (
	// POST (API) and GET (webpage).
	ENDPOINTSTRING_LINTCERT    = "lintcert"
	ENDPOINTSTRING_LINTTBSCERT = "linttbscert"
	ENDPOINTSTRING_LINTCRL     = "lintcrl"
	ENDPOINTSTRING_LINTTBSCRL  = "linttbscrl"
	ENDPOINTSTRING_LINTOCSP    = "lintocsp"
	ENDPOINTSTRING_LINTTBSOCSP = "linttbsocsp"

	// GET.
	ENDPOINTSTRING_FRONTPAGE = ""
	ENDPOINTSTRING_CSS       = "pkimetal.css"
	ENDPOINTSTRING_FAVICON   = "favicon.ico"
	ENDPOINTSTRING_MASCOT    = "mascot.jpg"
	ENDPOINTSTRING_LINTERS   = "linters"
	ENDPOINTSTRING_PROFILES  = "profiles"

	// GET (Monitoring).
	ENDPOINTSTRING_LIVEZ   = "livez"
	ENDPOINTSTRING_READYZ  = "readyz"
	ENDPOINTSTRING_METRICS = "metrics"
	ENDPOINTSTRING_BUILD   = "debug/build"
	ENDPOINTSTRING_CONFIG  = "debug/config"
)

const (
	ENDPOINT_LINTCERT Endpoint = iota
	ENDPOINT_LINTTBSCERT
	ENDPOINT_LINTCRL
	ENDPOINT_LINTTBSCRL
	ENDPOINT_LINTOCSP
	ENDPOINT_LINTTBSOCSP
)

var postEndpoint = map[string]Endpoint{
	ENDPOINTSTRING_LINTCERT:    ENDPOINT_LINTCERT,
	ENDPOINTSTRING_LINTTBSCERT: ENDPOINT_LINTTBSCERT,
	ENDPOINTSTRING_LINTCRL:     ENDPOINT_LINTCRL,
	ENDPOINTSTRING_LINTTBSCRL:  ENDPOINT_LINTTBSCRL,
	ENDPOINTSTRING_LINTOCSP:    ENDPOINT_LINTOCSP,
	ENDPOINTSTRING_LINTTBSOCSP: ENDPOINT_LINTTBSOCSP,
}

func (ri *RequestInfo) GetPOSTEndpoint(endpointString string) (ok bool) {
	ri.endpoint, ok = postEndpoint[endpointString]
	return
}
