[project]
name = "ftfy"
version = "_VERSION_"
description = "Fixes mojibake and other problems with Unicode, after the fact"
authors = [
  { name = "Robyn Speer", email = "rspeer@arborelia.net" },
]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry]
include = ["README.md", "CHANGELOG.md", "tests"]

[tool.poetry.dependencies]
python = ">=3.9,<4"
wcwidth = "^0.2.12"

[tool.poetry.group.dev.dependencies]
mypy = "^1.7.0"
Sphinx = "^4.3.2"
furo = ">=2021"
pytest = "^7.2.0"
black = ">=21"
flake8 = ">=3.0"

[tool.poetry.scripts]
ftfy = "ftfy.cli:main"

[project.urls]
Homepage = "https://ftfy.readthedocs.io/en/latest/"
Documentation = "https://ftfy.readthedocs.io/en/latest/"
Repository = "https://github.com/rspeer/python-ftfy"
Issues = "https://github.com/rspeer/python-ftfy/issues/"
Changelog = "https://github.com/rspeer/python-ftfy/blob/main/CHANGELOG.md"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = "badness.py"
