package linter

type SeverityLevel int

const (
	SEVERITYSTRING_META    = "meta"
	SEVERITYSTRING_DEBUG   = "debug"
	SEVERITYSTRING_INFO    = "info"
	SEVERITYSTRING_NOTICE  = "notice"
	SEVERITYSTRING_WARNING = "warning"
	SEVERITYSTRING_ERROR   = "error"
	SEVERITYSTRING_BUG     = "bug"
	SEVERITYSTRING_FATAL   = "fatal"
)

const (
	SEVERITY_META SeverityLevel = iota
	SEVERITY_DEBUG
	SEVERITY_INFO
	SEVERITY_NOTICE
	SEVERITY_WARNING
	SEVERITY_ERROR
	SEVERITY_BUG
	SEVERITY_FATAL
)

var SeverityString = []string{
	SEVERITYSTRING_META,
	SEVERITYSTRING_DEBUG,
	SEVERITYSTRING_INFO,
	SEVERITYSTRING_NOTICE,
	SEVERITYSTRING_WARNING,
	SEVERITYSTRING_ERROR,
	SEVERITYSTRING_BUG,
	SEVERITYSTRING_FATAL,
}

var Severity = map[string]SeverityLevel{
	"":                     SEVERITY_META, // Default=META.
	SEVERITYSTRING_META:    SEVERITY_META,
	SEVERITYSTRING_DEBUG:   SEVERITY_DEBUG,
	SEVERITYSTRING_INFO:    SEVERITY_INFO,
	SEVERITYSTRING_NOTICE:  SEVERITY_NOTICE,
	SEVERITYSTRING_WARNING: SEVERITY_WARNING,
	SEVERITYSTRING_ERROR:   SEVERITY_ERROR,
	SEVERITYSTRING_BUG:     SEVERITY_BUG,
	SEVERITYSTRING_FATAL:   SEVERITY_FATAL,
}
